### ISSUE TITLE
linodego version

### ISSUE THREAD

**Issue by ryansch** [hashicorp/packer-plugin-linode#6]
#### Overview of the Issue

It appears the linode/linodego had an accidental v1.0.0 release which was picked up by this project. See: https://github.com/linode/linodego/commit/fb6add3748146d1bb5b25ee6885aa087982bcff5

I think because of this, we won't see any of the updates in v0.26.1 or newer and latest is currently v0.28.1.

**Comment by nywilken** [comment]
Thanks for opening up this issue @ryansch I created https://github.com/hashicorp/packer-plugin-linode/pull/7 with the correct version of the linodego SDK. By chance are you able to build a local version of the binary from the PR and test against some of your test infrastructure?
